name: My Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "@{selected|HitDice}+@{selected|HitDice2}+@{selected|HitDice3}"
          replace: "@{HitDiceConcatenation}"
          include: "abilities/"
